### ISSUE TITLE
Cant run on Parrot OS

### ISSUE THREAD

**Issue by orderbird12** [radenvodka/Recsech#13]
Hi,
when i try your script, it turn the following out (php Recsech.php debug)

PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; Sdata has a deprecated constructor in /home/User/Recsech/tools/sdata-modules.php on line 8
PHP Warning:  mkdir(): File exists in /home/User/Recsech/tools/sdata-modules.php on line 56
PHP Fatal error:  Uncaught Error: Call to undefined function curl_multi_init() in /home/User/Recsech/tools/sdata-modules.php:58
Stack trace:
#0 /home/User/Recsech/tools/sdata-modules.php(181): Sdata->sdata()
#1 /home/User/Recsech/Recsech.php(16): require_once('/home/User/Recs...')
#2 {main}
  thrown in /home/User/Recsech/tools/sdata-modules.php on line 58

I run the newest php and curl is installed, too

Thanks

Ordi

**Comment by radenvodka** [comment]
pleas install php curl and use php 7

**Comment by orderbird12** [comment]
> I run the newest php and curl is installed, too

PHP 7.3.4-2 (cli) (built: Apr 13 2019 19:05:48)
curl is already the newest version (7.64.0-3)

**Comment by radenvodka** [comment]
use command : php -m

`C:\Users\Nokia 1337>php -m`

[PHP Modules]
bcmath
bz2
calendar
Core
ctype
`curl`
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
readline
Reflection
session
SimpleXML
SPL
standard
tokenizer
wddx
xml
xmlreader
xmlwriter
zip
zlib

**Comment by orderbird12** [comment]
Yep, Thanks! it wasnt installed. "sudo apt-get install php-curl" helped me. THANKS!

**Comment by radenvodka** [comment]
You're welcome, happy to be able to help you
