### ISSUE TITLE
Recsech PHP not executing, stays blank.

### ISSUE THREAD

**Issue by sh4nx0r** [radenvodka/Recsech#15]
This is a first time install for me and am I not able to make it run. 
Kindly check the screenshot with PHP version and recsech blank output.
<img width="369" alt="recsechoutput" src="https://user-images.githubusercontent.com/6489729/68565629-8bb40a80-046d-11ea-9923-7db8589336ec.PNG">

**Comment by PipeTenNathan** [comment]
I have also encountered this problem on'
` Kali linux Linux kali 4.19.0-kali5-amd64 #1 SMP Debian 4.19.37-6kali1 (2019-07-22) x86_64 GNU/Linux`
php -v
```
PHP 7.3.10-1+b1 (cli) (built: Oct 13 2019 23:50:57) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.10, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.10-1+b1, Copyright (c) 1999-2018, by Zend Technologies
```

**Comment by radenvodka** [comment]
install php curl and for check modules using command : php -m
