### ISSUE TITLE
collor legend

### ISSUE THREAD

**Issue by UdaryanDotCom** [radenvodka/Recsech#16]
hai im using using your github,I want to ask if there is a way to read the results of this Recsech scanning, does the red domain mean the domain mark xss protection or how, can be given help for its use, can you email me to apollosolarsun@gmail.com

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by radenvodka** [comment]
You can read at https://www.thesslstore.com/blog/http-security-headers/ to implement the security of your headers.
